// Copyright (c) 2024 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.

/**
* @addtogroup CTRebootVM
* @{
  Class CTRebootVM implements \link ITRebootVM \endlink interface.

  The class ID `TRebootVM` is a platform service in Mink daemon.
*/

// This class provides an interface to shutdown/reboot VM.
//

const uint32 CTRebootVM_UID = 808;

/** @} */

