/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */

#pragma once

#ifdef _WIN32
// "C:\\work\\apcc\\"
// "C:\\work\\apcc\\wifi\\"
// "C:\\work\\apcc\\supplicant\\"
#define DEFAULT_APCC_ROOT   "C:\\work\\apcc\\wifi\\"
#elif __linux__
#define DEFAULT_APCC_ROOT   "~/apcc/"
#elif ANDROID
#define DEFAULT_APCC_ROOT   "/data/apcc/"
#endif

#define DEFAULT_APCC_AIDL_PATH          (DEFAULT_APCC_ROOT "aidl")
#define DEFAULT_APCC_PROTO_PATH         (DEFAULT_APCC_ROOT "proto")
#define DEFAULT_APCC_GEN_SOURCE_PATH    (DEFAULT_APCC_ROOT "gen")

/*******************************************************************************
 * relative path definition under source code path generated by apcc
 *******************************************************************************/
/* 0. folder: . */
#define FOLDER_CURRENT_DIR              "."

/* 1. folder: client */
#define FOLDER_CLIENT                   "client"
#ifdef _WIN32
#define FOLDER_CLIENT_AIDL              "client\\aidl"
#define FOLDER_CLIENT_AIDL_API          "client\\aidl\\api"
#define FOLDER_CLIENT_AIDL_UTIL         "client\\aidl\\util"
#else
#define FOLDER_CLIENT_AIDL              "client/aidl"
#define FOLDER_CLIENT_AIDL_API          "client/aidl/api"
#define FOLDER_CLIENT_AIDL_UTIL         "client/aidl/util"
#endif

/* 2. folder: include */
#define FOLDER_INCLUDE                  "include"

/* 3. folder: message */
#define FOLDER_MESSAGE                  "message"
#ifdef _WIN32
#define FOLDER_MESSAGE_INCLUDE          "message\\include"
#define FOLDER_MESSAGE_SRC              "message\\src"
#define FOLDER_MESSAGE_TEST             "message\\test"
#else
#define FOLDER_MESSAGE_INCLUDE          "message/include"
#define FOLDER_MESSAGE_SRC              "message/src"
#define FOLDER_MESSAGE_TEST             "message/test"
#endif

/* 4. folder: server */
#define FOLDER_SERVER                   "server"
#ifdef _WIN32
#define FOLDER_SERVER_API               "server\\api"
#define FOLDER_SERVER_IMPL              "server\\impl"
#define FOLDER_SERVER_LIB               "server\\lib"
#define FOLDER_SERVER_LIB_INCLUDE       "server\\lib\\include"
#define FOLDER_SERVER_LIB_UTIL          "server\\lib\\util"
#define FOLDER_SERVER_MAIN              "server\\main"
#else
#define FOLDER_SERVER_API               "server/api"
#define FOLDER_SERVER_IMPL              "server/impl"
#define FOLDER_SERVER_LIB               "server/lib"
#define FOLDER_SERVER_LIB_INCLUDE       "server/lib/include"
#define FOLDER_SERVER_LIB_UTIL          "server/lib/util"
#define FOLDER_SERVER_MAIN              "server/main"
#endif

/*******************************************************************************
 * source file's name for hal rpc
 *******************************************************************************/

/* 0. folder: . */
#define FILE_ANDROID_BP                 "Android.bp"

/* 1. folder: client */
#define FILE_HAL_API_HEADER             "hal_api.h"
#define FILE_HAL_RPC_HEADER             "hal_rpc.h"
#define FILE_HAL_RPC_SOURCE             "hal_rpc.cpp"
#define FILE_HAL_RPC_SERVICE_HEADER     "hal_rpc_service.h"
#define FILE_HAL_RPC_SERVICE_SOURCE     "hal_rpc_service.cpp"
#define FILE_HAL_STATUS_UTIL_HEADER     "hal_status_util.h"
#define FILE_HAL_STATUS_UTIL_SOURCE     "hal_status_util.cpp"

#define FILE_HAL_LIB_HEADER             "hal_lib.h"
#define FILE_HAL_MSG_TRANSPORT_HEADER   "hal_msg_transport.h"
#define FILE_HAL_PROTO_LIB_HEADER       "hal_proto_lib.h"

#define FILE_HAL_LIB_SOURCE             "hal_lib.cpp"
#define FILE_HAL_PROTO_LIB_SOURCE       "hal_proto_lib.cpp"

/* 2. folder: include */
#define FILE_HAL_MESSAGE_DEF_HEADER     "hal_message_def.h"
#define FILE_HAL_SOMEIP_DEF_HEADER      "hal_someip_def.h"

/* 3. folder: message */
#define FILE_HAL_MSG_HEADER             "hal_msg.h"

#define FILE_HAL_MSG_SOURCE             "hal_msg.cpp"

#define FILE_HAL_MSG_TEST_SOURCE        "hal_message_test.cpp"

/* 4. folder: server */
#define FILE_SERVICE_SOURCE             "service.cpp"
#define FILE_HAL_SERVICE_HEADER         "hal_service.h"
#define FILE_HAL_SERVICE_SOURCE         "hal_service.cpp"
#define FILE_HAL_RPC_SERVER_HEADER      "hal_rpc_server.h"
#define FILE_HAL_RPC_SERVER_SOURCE      "hal_rpc_server.cpp"
#define FILE_HAL_IMPL_HEADER            "hal.h"
#define FILE_HAL_IMPL_SOURCE            "hal.cpp"
#define FILE_HAL_SERVER_API_HEADER      "hal_api.h"

/*******************************************************************************
 * misc
 *******************************************************************************/

#define ENABLE_HAL_IMPL                 true

#define IS_CLEAR_CALLBACK_REQUIRED      false

#define EXIST_CREATE_HAL_STATUS_FUNC    true

#define AIDL_RETURN_NAME                "_aidl_return"

#define RESULT_NAME                     "result"

#define RES_NAME                        "res"

#define HAL_INSTANCE1                   "instance1"

#define HAL_PROTO_LIB_FUNC_SUFFIX       "_struct"

#define HAL_PROTO_LIB_DEF_SUFFIX        "Send"

#define HAL_MSG_TRANSPORT_SUFFIX        "MsgTransport"

#define HAL_MSG_SERIALIZE               "Serialize"
#define HAL_MSG_PARSE                   "Parse"
#define HAL_MSG_FREE                    "Free"
#define HAL_MSG_PAYLOAD                 "Payload"

#define MSG_NAME                        "msg"
#define MSG_ALIAS_NAME                  "msg_a"
#define TYPE_NAME                       "type"
#define DATA_NAME                       "data"
#define LENGTH_NAME                     "length"
#define MSG_DATA_NAME                   "msg_data"
#define MSG_LENGTH_NAME                 "msg_length"

#define HAL_STATUS_CODE_SUFFIX          "StatusCode"
#define STATUS_NAME                     "status"
#define STATUS_VAR                      "_status"

#define HAL_STATUS_INFO_TYPE            "const string&"

#define HAL_DEFAULT_INSTANCE_SUFFIX     "DEFAULT_INSTANCE"
#define HAL_INSTANCE1_SUFFIX            "INSTANCE1"

#define HAL_CFM_PARAM_SUFFIX            "CfmParam"

#define HAL_MSG_TYPE_SUFFIX             "Msg"

#define HAL_PAYLOAD_SUFFIX              "Payload"

#define HAL_SERVICE_ID_SUFFIX           "_SERVICE_ID"

#define RPC_NAME                        "Rpc"

#define IS_RPC_ENABLED_FUNC             "isRpcEnabled"
#define CALL_IS_RPC_ENABLED_FUNC        (IS_RPC_ENABLED_FUNC "()")

#define INTERNAL_FUNC_SUFFIX            "Internal"

#define PARAM_INSTANCE_NAME             "instance_name"

#define HAL_API_PARAM_TYPE              "const char*"
#define HAL_API_PARAM_NAME              PARAM_INSTANCE_NAME

#define HAL_INST_PARAM_TYPE             "const string&"
#define HAL_INST_PARAM_NAME             PARAM_INSTANCE_NAME

#define CREATE_NAME                     "create"
#define ADD_NAME                        "add"

#define REMOVE_NAME                     "remove"
#define DELETE_NAME                     "delete"

#define GET_NAME                        "get"

#define MESSAGE_TYPE_NAME               "message_type"
#define PAYLOAD_NAME                    "payload"
#define PAYLOAD_VAR_NAME                "_payload"
#define BUF_NAME                        "buf"
#define MV_NAME                         "mv"
#define SESSION_ID_NAME                 "session_id"

#define HAL_REQ_BASE_SUFFIX             "_REQ_BASE"
#define HAL_REQ_COUNT_SUFFIX            "_REQ_COUNT"
#define HAL_IND_BASE_SUFFIX             "_IND_BASE"
#define HAL_IND_COUNT_SUFFIX            "_IND_COUNT"
#define HAL_CFM_BASE_SUFFIX             "_CFM_BASE"
#define HAL_CFM_COUNT_SUFFIX            "_CFM_COUNT"
#define HAL_CFM_INDEX_SUFFIX            "_CFM_INDEX"
#define HAL_UP_REQ_BASE_SUFFIX          "_UPSTREAM_REQ_BASE"
#define HAL_UP_REQ_COUNT_SUFFIX         "_UPSTREAM_REQ_COUNT"
#define HAL_DOWN_CFM_BASE_SUFFIX        "_DOWNSTREAM_CFM_BASE"
#define HAL_DOWN_CFM_COUNT_SUFFIX       "_DOWNSTREAM_CFM_COUNT"

/* hal someip def */
#define SOMEIP_COMMON_DEF_HEADER        "someip_common_def.h"

#define HAL_INSTANCE_ID_BASE_SUFFIX     "_INSTANCE_ID_BASE"
#define HAL_INSTANCE_ID_BASE_VAL        "((uint16_t) 0x1100)"

#define HAL_EVENTGROUP_ID_BASE_SUFFIX   "_EVENTGROUP_ID_BASE"
#define HAL_EVENTGROUP_ID_BASE_VAL      "(HAL_EVENTGROUP_ID_BASE)"

#define HAL_INSTANCE_ID_SUFFIX          "_INSTANCE_ID"
#define HAL_INSTANCE1_ID_SUFFIX         "_INSTANCE1_ID"

#define HAL_EVENTGROUP_ID_SUFFIX        "_EVENTGROUP_ID"

#define HAL_EVENT_ID_NUMBER_SUFFIX      "_EVENT_ID_NUMBER"

#define HAL_CLIENT_APP_NAME_SUFFIX      "_CLIENT_APP_NAME"
#define HAL_CLIENT_APP_NAME_VAL_SUFFIX  "_client"

#define HAL_SERVER_APP_NAME_SUFFIX      "_SERVER_APP_NAME"
#define HAL_SERVER_APP_NAME_VAL_SUFFIX  "_service"

#define HAL_SERVICE_ID_NAME_SUFFIX      "_SERVICE_ID"

#define HAL_MODE_PROPERTY_NAME_PREFIX   "persist.vendor."
#define HAL_MODE_PROPERTY_NAME_SUFFIX   ".hal_mode"

#define EVENT_UTIL_HEADER               "event_util.h"
#define LOG_COMMON_HEADER               "log_common.h"
#define MESSAGE_SCHED_HEADER            "message_sched.h"
#define PROTO_MESSAGE_HEADER            "proto_message.h"
#define SOMEIP_API_HEADER               "someip_api.h"
#define PROTO_COMMON_HEADER             "proto_common.h"
#define HAL_UTIL_HEADER                 "hal_util.h"

#define PROTO_MESSAGE_CREATE_FUNC       "ProtoMessageCreate"

#define INSTANCE_NAME                   "Instance"

#define PARAM_STRUCT_SUFFIX             "Param"

#define PARAM_VAR_NAME                  "param"

#define CALLBACK_NAME                   "callback"
#define CALLBACK_VAR_NAME               "callback_"
#define CALLBACKS_NAME                  "callbacks"
#define CALLBACKS_VAR_NAME              "callbacks_"
#define INSTANCE_INDEX_NAME             "instance_index"
#define EVENT_HANDLE_NAME               "eventHandle"
#define CFM_PARAM_NAME                  "cfmParam"

#define INDEX_NAME                      "index"
#define STATUS_CODE_NAME                "status_code"
#define INFO_NAME                       "info"
#define INFO_VAR                        "_info"

#define SRC_PARAM_NAME                  "src_param"
#define DST_PARAM_NAME                  "dst_param"

#define STRING_2_INT_FUNC_NAME          "String2Int"
#define STRING_2_BOOL_FUNC_NAME         "String2Bool"

#define EVENT_HANDLE_STRUCT_NAME        "EventHandle"

#define EVENT_CREATE_FUNC_NAME          "EventCreate"
#define EVENT_SET_FUNC_NAME             "EventSet"
#define EVENT_WAIT_FUNC_NAME            "EventWait"
#define EVENT_DESTROY_FUNC_NAME         "EventDestroy"
#define EVENT_WAIT_INFINITE_NAME        "EVENT_WAIT_INFINITE"

#define HAL_MSG_SCHED_HANDLER_SUFFIX    "_message_sched_handler"

#define MSG_SCHED_REGISTER_INFO_NAME    "MessageSchedRegisterInfo"

#define MSG_SCHED_INIT_FUNC_NAME        "MessageSchedInit"
#define MSG_SCHED_SEND_FUNC_NAME        "MessageSchedSend"
#define MSG_SCHED_DEINIT_FUNC_NAME      "MessageSchedDeinit"

#define SIZE_NAME                       "size"
#define MSG_HANDLER_NAME                "messageHandler"

#define INIT_SOMEIP_CONTEXT_FUNC_NAME   "init_someip_context"
#define SOMEIP_CONTEXT_NAME             "SomeipContext"
#define SOMEIP_CONTEXT_REF              "SomeipContext&"
#define SOMEIP_CONTEXT_VAR              "someip_context_"
#define SOMEIP_APP_NAME_VAR             "someip_app_name_"
#define SOMEIP_EVENT_ID_VAR             "event_id"

#define SOMEIP_MAP_NAME                 "SomeipMap"

#define INIT_SOMEIP_REGISTER_INFO_FUNC_NAME "init_someip_register_info"
#define SOMEIP_REGISTER_INFO_NAME       "SomeipRegisterInfo"
#define SOMEIP_REGISTER_INFO_REF        "SomeipRegisterInfo&"
#define REGISTER_INFO_NAME              "registerInfo"

#define SOMEIP_INIT_FUNC_NAME           "someip_init"
#define SOMEIP_OPEN_FUNC_NAME           "someip_open"
#define SOMEIP_SEND_FUNC_NAME           "someip_send"
#define SOMEIP_CLOSE_FUNC_NAME          "someip_close"
#define SOMEIP_DEINIT_FUNC_NAME         "someip_deinit"

#define PROTO_MSG_PARSE_FUNC_NAME       "ProtoMessageParse"
#define PROTO_MSG_DELETE_FUNC_NAME      "ProtoMessageDelete"

#define INIT_LOG_FUNC_NAME              "InitLog"
#define DEINIT_LOG_FUNC_NAME            "DeinitLog"

#define GET_MAX_RESPONSE_NAME           "getMaxResponse"

#define INST_NAME                       "inst"

#define EVENT_NAME                      "event"

#define VAR_SUFFIX                      '_'

#define COMMENT_TODO                    "/* TODO */"

#define COMMENT_HAL_REQ                 "/* hal req */"
#define COMMENT_HAL_REQ_SERIALIZE       "/* hal req (serialize) */"
#define COMMENT_HAL_REQ_PARSE           "/* hal req (parse) */"

#define COMMENT_HAL_CFM                 "/* hal cfm */"
#define COMMENT_HAL_CFM_SERIALIZE       "/* hal cfm (serialize) */"
#define COMMENT_HAL_CFM_PARSE           "/* hal cfm (parse) */"

#define COMMENT_HAL_IND                 "/* hal ind */"
#define COMMENT_HAL_IND_SERIALIZE       "/* hal ind (serialize) */"
#define COMMENT_HAL_IND_PARSE           "/* hal ind (parse) */"

#define COMMENT_HAL_UP_REQ              "/* hal req (upstream) */"
#define COMMENT_HAL_UP_REQ_SERIALIZE    "/* hal req (upstream, serialize) */"
#define COMMENT_HAL_UP_REQ_PARSE        "/* hal req (upstream, parse) */"

#define COMMENT_HAL_DOWN_CFM            "/* hal cfm (downstream) */"
#define COMMENT_HAL_DOWN_CFM_SERIALIZE  "/* hal cfm (downstream, serialize) */"
#define COMMENT_HAL_DOWN_CFM_PARSE      "/* hal cfm (downstream, parse) */"

#define COMMENT_UNKNOWN_MESSAGE_TYPE    "/* unknown message type */"
