#pragma once
// Copyright (c) 2016-2019,2022-2023 Qualcomm Technologies, Inc.

// All Rights Reserved.

// Confidential and Proprietary - Qualcomm Technologies, Inc.

// AUTOGENERATED FILE: DO NOT EDIT

#include <cstdint>
#include "object.h"
#include "proxy_base.hpp"
#include "IIO.hpp"
#include "ICredentials.hpp"

class IIClientEnv {
   public:
    static const int32_t ERROR_COMMONLIBS_ALREADY_LOADED = INT32_C(10);
    static const int32_t ERROR_APP_REGION_ALREADY_SET = INT32_C(11);

    virtual ~IIClientEnv() {}

    virtual int32_t open(uint32_t uid_val, ProxyBase &obj_ref) = 0;
    virtual int32_t registerLegacy(const void* credentials_ptr, size_t credentials_len, ProxyBase &clientEnv_ref) = 0;
    virtual int32_t registerAsClient(const IIO &credentials_ref, ProxyBase &clientEnv_ref) = 0;
    virtual int32_t registerWithWhitelist(const IIO &credentials_ref, const uint32_t* uids_ptr, size_t uids_len, ProxyBase &clientEnv_ref) = 0;
    virtual int32_t notifyDomainChange() = 0;
    virtual int32_t registerWithCredentials(const ICredentials &credentials_ref, ProxyBase &clientEnv_ref) = 0;
    virtual int32_t loadCmnlibFromBuffer(const void* cmnlibElf_ptr, size_t cmnlibElf_len) = 0;
    virtual int32_t configTaRegion(uint64_t appRgnAddr_val, uint32_t appRgnSize_val) = 0;
    virtual int32_t adciAccept() = 0;
    virtual int32_t adciShutdown() = 0;

   protected:
    static const ObjectOp OP_open = 0;
    static const ObjectOp OP_registerLegacy = 1;
    static const ObjectOp OP_registerAsClient = 2;
    static const ObjectOp OP_registerWithWhitelist = 3;
    static const ObjectOp OP_notifyDomainChange = 4;
    static const ObjectOp OP_registerWithCredentials = 5;
    static const ObjectOp OP_loadCmnlibFromBuffer = 6;
    static const ObjectOp OP_configTaRegion = 7;
    static const ObjectOp OP_adciAccept = 8;
    static const ObjectOp OP_adciShutdown = 9;
};

class IClientEnv : public IIClientEnv, public ProxyBase {
   public:
    IClientEnv() {}
    IClientEnv(Object impl) : ProxyBase(impl) {}
    virtual ~IClientEnv() {}

    virtual int32_t open(uint32_t uid_val, ProxyBase &obj_ref) {
        ObjectArg a[2]={{{0,0}}};
        a[0].b = (ObjectBuf) {&uid_val, sizeof(uint32_t)};

        int32_t result = invoke(OP_open, a, ObjectCounts_pack(1, 0, 0, 1));
        if (Object_OK != result) { return result; }

        obj_ref.consume(a[1].o);

        return result;
    }

    virtual int32_t registerLegacy(const void* credentials_ptr, size_t credentials_len, ProxyBase &clientEnv_ref) {
        ObjectArg a[2]={{{0,0}}};
        a[0].bi = (ObjectBufIn) {credentials_ptr, credentials_len * 1};

        int32_t result = invoke(OP_registerLegacy, a, ObjectCounts_pack(1, 0, 0, 1));
        if (Object_OK != result) { return result; }

        clientEnv_ref.consume(a[1].o);

        return result;
    }

    virtual int32_t registerAsClient(const IIO &credentials_ref, ProxyBase &clientEnv_ref) {
        ObjectArg a[2]={{{0,0}}};
        a[0].o = credentials_ref.get();

        int32_t result = invoke(OP_registerAsClient, a, ObjectCounts_pack(0, 0, 1, 1));
        if (Object_OK != result) { return result; }

        clientEnv_ref.consume(a[1].o);

        return result;
    }

    virtual int32_t registerWithWhitelist(const IIO &credentials_ref, const uint32_t* uids_ptr, size_t uids_len, ProxyBase &clientEnv_ref) {
        ObjectArg a[3]={{{0,0}}};
        a[1].o = credentials_ref.get();
        a[0].bi = (ObjectBufIn) {uids_ptr, uids_len * sizeof(uint32_t)};

        int32_t result = invoke(OP_registerWithWhitelist, a, ObjectCounts_pack(1, 0, 1, 1));
        if (Object_OK != result) { return result; }

        clientEnv_ref.consume(a[2].o);

        return result;
    }

    virtual int32_t notifyDomainChange() {
        return invoke(OP_notifyDomainChange, 0, 0);
    }

    virtual int32_t registerWithCredentials(const ICredentials &credentials_ref, ProxyBase &clientEnv_ref) {
        ObjectArg a[2]={{{0,0}}};
        a[0].o = credentials_ref.get();

        int32_t result = invoke(OP_registerWithCredentials, a, ObjectCounts_pack(0, 0, 1, 1));
        if (Object_OK != result) { return result; }

        clientEnv_ref.consume(a[1].o);

        return result;
    }

    virtual int32_t loadCmnlibFromBuffer(const void* cmnlibElf_ptr, size_t cmnlibElf_len) {
        ObjectArg a[1]={{{0,0}}};
        a[0].bi = (ObjectBufIn) {cmnlibElf_ptr, cmnlibElf_len * 1};

        return invoke(OP_loadCmnlibFromBuffer, a, ObjectCounts_pack(1, 0, 0, 0));
    }

    virtual int32_t configTaRegion(uint64_t appRgnAddr_val, uint32_t appRgnSize_val) {
        ObjectArg a[1]={{{0,0}}};
        struct s1 {
            uint64_t m_appRgnAddr;
            uint32_t m_appRgnSize;
        } i;
        a[0].b = (ObjectBuf) {&i, 12};
        i.m_appRgnAddr = appRgnAddr_val;
        i.m_appRgnSize = appRgnSize_val;

        return invoke(OP_configTaRegion, a, ObjectCounts_pack(1, 0, 0, 0));
    }

    virtual int32_t adciAccept() {
        return invoke(OP_adciAccept, 0, 0);
    }

    virtual int32_t adciShutdown() {
        return invoke(OP_adciShutdown, 0, 0);
    }

};

