#Strait 2.5 specific build flag
ifeq ($(TARGET_BOARD_PLATFORM),blair)
TARGET_ENABLE_QTEECONNECTOR := true
TARGET_ENABLE_QTEECONNECTOR_SMCINVOKE := true
endif

#Lanai specific build flag
ifeq ($(TARGET_BOARD_PLATFORM),pineapple)
TARGET_ENABLE_QTEECONNECTOR := false
TARGET_ENABLE_QTEECONNECTOR_SMCINVOKE := false
endif

#Kalpeni specific build flag
ifeq ($(TARGET_BOARD_PLATFORM),pitti)
TARGET_ENABLE_QTEECONNECTOR := false
TARGET_ENABLE_QTEECONNECTOR_SMCINVOKE := false
endif

#Milos specific build flag
ifeq ($(TARGET_BOARD_PLATFORM),volcano)
TARGET_ENABLE_QTEECONNECTOR := false
TARGET_ENABLE_QTEECONNECTOR_SMCINVOKE := false
endif

#Matrix specific build flag
ifeq ($(TARGET_BOARD_PLATFORM),niobe)
TARGET_ENABLE_QTEECONNECTOR := false
TARGET_ENABLE_QTEECONNECTOR_SMCINVOKE := false
endif

#pakala specific build flag
ifeq ($(TARGET_BOARD_PLATFORM),sun)
TARGET_ENABLE_QTEECONNECTOR := false
TARGET_ENABLE_QTEECONNECTOR_SMCINVOKE := false
endif

#Hana gen3 specific build flag
ifeq ($(TARGET_BOARD_PLATFORM),msmnile)
TARGET_ENABLE_QTEECONNECTOR := true
TARGET_ENABLE_QTEECONNECTOR_SMCINVOKE := false
endif

#Talos AU specific build flag
ifeq ($(TARGET_BOARD_PLATFORM),$(MSMSTEPPE))
TARGET_ENABLE_QTEECONNECTOR := true
TARGET_ENABLE_QTEECONNECTOR_SMCINVOKE := false
endif

#Lemans IVI specific build flag
ifeq ($(TARGET_BOARD_PLATFORM),gen4)
ifneq ($(TARGET_USES_GY), true)
TARGET_ENABLE_QTEECONNECTOR := true
TARGET_ENABLE_QTEECONNECTOR_SMCINVOKE := false
endif #TARGET_USES_GY
endif

ifeq ($(TARGET_BOARD_PLATFORM),gen5)
TARGET_ENABLE_QTEECONNECTOR := true
TARGET_ENABLE_QTEECONNECTOR_SMCINVOKE := false
endif

#Monaco specific build flag
ifeq ($(TARGET_BOARD_PLATFORM),monaco)
TARGET_ENABLE_QTEECONNECTOR := true
TARGET_ENABLE_QTEECONNECTOR_SMCINVOKE := false
endif
