LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := ccidbgr
LOCAL_MODULE_TAGS := optional

LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/bin

LOCAL_C_INCLUDES += $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr/include/ais
ifeq ($(TARGET_KERNEL_VERSION),$(filter 5.15 6.1,$(TARGET_KERNEL_VERSION)))
LOCAL_HEADER_LIBRARIES += qti_ais_kernel_uapi
endif

LOCAL_ADDITIONAL_DEPENDENCIES += $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr

LOCAL_CFLAGS +=-lpthread

LOCAL_SRC_FILES := \
    la/ccidbgr.c

include $(BUILD_EXECUTABLE)
