/**
 * Copyright (c) 2023 Qualcomm Technologies, Inc. All Rights Reserved.
 * Qualcomm Technologies Proprietary and Confidential.
 */
/** @file  IDRMSample_invoke.h */
/**
 * @brief
 * IDRMSample interface provides an interface to the sample DRM implementation
 */
/**
 * Supported Generic Encryption algorithms
 */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"
#include "IDRMSample.h"

#define IDRMSample_DEFINE_INVOKE(func, prefix, type) \
  int32_t func(ObjectCxt h, ObjectOp op, ObjectArg *a, ObjectCounts k) \
  { \
    type me = (type) h; \
    switch (ObjectOp_methodID(op)) { \
      case Object_OP_release: { \
        if (k != ObjectCounts_pack(0, 0, 0, 0)) { \
          break; \
        } \
        return prefix##release(me); \
      } \
      case Object_OP_retain: { \
        if (k != ObjectCounts_pack(0, 0, 0, 0)) { \
          break; \
        } \
        return prefix##retain(me); \
      } \
      case IDRMSample_OP_Crypto: { \
        if (k != ObjectCounts_pack(1, 0, 2, 0) || \
          a[0].b.size != 40) { \
          break; \
        } \
        const struct { \
          IDRMBufferInfo m_inputBuf; \
          IDRMBufferInfo m_outputBuf; \
          IDRMCryptoInfo m_cryptoData; \
        } *i = a[0].b.ptr; \
        return prefix##Crypto(me, &i->m_cryptoData, &i->m_inputBuf, &i->m_outputBuf, a[1].o, a[2].o); \
      } \
      case IDRMSample_OP_SFSTest: { \
        if (k != ObjectCounts_pack(0, 0, 0, 0)) { \
          break; \
        } \
        return prefix##SFSTest(me); \
      } \
      case IDRMSample_OP_RPMBTest: { \
        if (k != ObjectCounts_pack(0, 0, 0, 0)) { \
          break; \
        } \
        return prefix##RPMBTest(me); \
      } \
      case IDRMSample_OP_HDCPEnforcementTest: { \
        if (k != ObjectCounts_pack(0, 0, 0, 0)) { \
          break; \
        } \
        return prefix##HDCPEnforcementTest(me); \
      } \
    } \
    return Object_ERROR_INVALID; \
  }


