/**
 * Copyright (c) 2023 Qualcomm Technologies, Inc. All Rights Reserved.
 * Qualcomm Technologies Proprietary and Confidential.
 */
/** @file  IDRMSample.h */
/**
 * @brief
 * IDRMSample interface provides an interface to the sample DRM implementation
 */
/**
 * Supported Generic Encryption algorithms
 */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define DRM_ENCRYPTION_TYPE_CENC UINT32_C(0)

#define DRM_ENCRYPTION_TYPE_CBCS UINT32_C(1)

#define DRM_CIPHER_OP_DECRYPT UINT32_C(0)

#define DRM_CIPHER_OP_ENCRYPT UINT32_C(1)

typedef struct {
  uint32_t cipherOP;
  uint32_t cipherMode;
} IDRMCryptoInfo;

typedef struct {
  uint64_t va;
  uint32_t size;
  uint32_t secure;
} IDRMBufferInfo;

#define IDRMSample_ERROR_LICENSE_NOT_FOUND INT32_C(10)

#define IDRMSample_OP_Crypto 0
#define IDRMSample_OP_SFSTest 1
#define IDRMSample_OP_RPMBTest 2
#define IDRMSample_OP_HDCPEnforcementTest 3
#define IDRMSample_OP_CPZLicenseTest 4

static inline int32_t
IDRMSample_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IDRMSample_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IDRMSample_Crypto(Object self, const IDRMCryptoInfo *cryptoData_ptr, const IDRMBufferInfo *inputBuf_ptr, const IDRMBufferInfo *outputBuf_ptr, Object inMemObj_val, Object outMemObj_val)
{
  ObjectArg a[3]={{{0,0}}};
  struct {
    IDRMBufferInfo m_inputBuf;
    IDRMBufferInfo m_outputBuf;
    IDRMCryptoInfo m_cryptoData;
  } i = {0};
  a[0].b = (ObjectBuf) { &i, 40 };
  i.m_cryptoData = *cryptoData_ptr;
  i.m_inputBuf = *inputBuf_ptr;
  i.m_outputBuf = *outputBuf_ptr;
  a[1].o = inMemObj_val;
  a[2].o = outMemObj_val;

  return Object_invoke(self, IDRMSample_OP_Crypto, a, ObjectCounts_pack(1, 0, 2, 0));
}

static inline int32_t
IDRMSample_SFSTest(Object self)
{
  return Object_invoke(self, IDRMSample_OP_SFSTest, 0, 0);
}

static inline int32_t
IDRMSample_RPMBTest(Object self)
{
  return Object_invoke(self, IDRMSample_OP_RPMBTest, 0, 0);
}

static inline int32_t
IDRMSample_HDCPEnforcementTest(Object self)
{
  return Object_invoke(self, IDRMSample_OP_HDCPEnforcementTest, 0, 0);
}

static inline int32_t
IDRMSample_CPZLicenseTest(Object self)
{
  return Object_invoke(self, IDRMSample_OP_CPZLicenseTest, 0, 0);
}
