/**
 * Copyright (c) 2023 Qualcomm Technologies, Inc. All Rights Reserved.
 * Qualcomm Technologies Proprietary and Confidential.
 */

/** @file  IDRMSample.idl */

/**
 * @brief
 * IDRMSample interface provides an interface to the sample DRM implementation
 */

/**
 * Supported Generic Encryption algorithms
 */
const uint32 DRM_ENCRYPTION_TYPE_CENC = 0;
const uint32 DRM_ENCRYPTION_TYPE_CBCS = 1;

/**
 * Supported Crypto operations
 */
const uint32 DRM_CIPHER_OP_DECRYPT = 0;
const uint32 DRM_CIPHER_OP_ENCRYPT = 1;

/** Crypto Operation details */
struct IDRMCryptoInfo {
    uint32 cipherOP;
    uint32 cipherMode;
};

/** DRM buffer details */
struct IDRMBufferInfo {
    uint64 va;
    uint32 size;
    uint32 secure;
};

interface IDRMSample {
   /**
   * @addtogroup IDRMSample
   * @{
   */

   /**
    Interface to depict usage of crypto interfaces for a DRM TA.
    @param [in] cryptoData    crypto context data.
    @param [in] inputBuf      input buffer details.
    @param [in] outputBuf     output buffer details.
    @param [in] inMemObj      input buffer memory object.
    @param [in] outMemObj     output buffer memory object.

    @return
    Object_OK on success. Any other error code on failure.
   */
	method Crypto(in IDRMCryptoInfo cryptoData, in IDRMBufferInfo inputBuf, in IDRMBufferInfo outputBuf, in interface inMemObj, in interface outMemObj);

	/**
    Interface to depict usage of the secure file system (SFS) storage.

    @return
    Object_OK on success. Any other error code on failure.
   */
	method SFSTest();

	/**
    Interface to depict usage of the RPMB storage.

    @return
    Object_OK on success. Any other error code on failure.
   */
	method RPMBTest();

	/**
    Interface to depict usage of HDCP enforcements from a DRM TA.

    @return
    Object_OK on success. Any other error code on failure.
   */
	method HDCPEnforcementTest();

	/** @} */ /* end_addtogroup IDRMSample */
};


