// Copyright (c) 2016-2019,2022-2023 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"
#include "IIO.h"
#include "ICredentials.h"

#define IClientEnv_ERROR_COMMONLIBS_ALREADY_LOADED INT32_C(10)
#define IClientEnv_ERROR_APP_REGION_ALREADY_SET INT32_C(11)

#define IClientEnv_OP_open 0
#define IClientEnv_OP_registerLegacy 1
#define IClientEnv_OP_registerAsClient 2
#define IClientEnv_OP_registerWithWhitelist 3
#define IClientEnv_OP_notifyDomainChange 4
#define IClientEnv_OP_registerWithCredentials 5
#define IClientEnv_OP_loadCmnlibFromBuffer 6
#define IClientEnv_OP_configTaRegion 7
#define IClientEnv_OP_adciAccept 8
#define IClientEnv_OP_adciShutdown 9

static inline int32_t
IClientEnv_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IClientEnv_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IClientEnv_open(Object self, uint32_t uid_val, Object *obj_ptr)
{
  ObjectArg a[2]={{{0,0}}};
  a[0].b = (ObjectBuf) { &uid_val, sizeof(uint32_t) };

  int32_t result = Object_invoke(self, IClientEnv_OP_open, a, ObjectCounts_pack(1, 0, 0, 1));

  *obj_ptr = a[1].o;

  return result;
}

static inline int32_t
IClientEnv_registerLegacy(Object self, const void *credentials_ptr, size_t credentials_len, Object *clientEnv_ptr)
{
  ObjectArg a[2]={{{0,0}}};
  a[0].bi = (ObjectBufIn) { credentials_ptr, credentials_len * 1 };

  int32_t result = Object_invoke(self, IClientEnv_OP_registerLegacy, a, ObjectCounts_pack(1, 0, 0, 1));

  *clientEnv_ptr = a[1].o;

  return result;
}

static inline int32_t
IClientEnv_registerAsClient(Object self, Object credentials_val, Object *clientEnv_ptr)
{
  ObjectArg a[2]={{{0,0}}};
  a[0].o = credentials_val;

  int32_t result = Object_invoke(self, IClientEnv_OP_registerAsClient, a, ObjectCounts_pack(0, 0, 1, 1));

  *clientEnv_ptr = a[1].o;

  return result;
}

static inline int32_t
IClientEnv_registerWithWhitelist(Object self, Object credentials_val, const uint32_t *uids_ptr, size_t uids_len, Object *clientEnv_ptr)
{
  ObjectArg a[3]={{{0,0}}};
  a[1].o = credentials_val;
  a[0].bi = (ObjectBufIn) { uids_ptr, uids_len * sizeof(uint32_t) };

  int32_t result = Object_invoke(self, IClientEnv_OP_registerWithWhitelist, a, ObjectCounts_pack(1, 0, 1, 1));

  *clientEnv_ptr = a[2].o;

  return result;
}

static inline int32_t
IClientEnv_notifyDomainChange(Object self)
{
  return Object_invoke(self, IClientEnv_OP_notifyDomainChange, 0, 0);
}

static inline int32_t
IClientEnv_registerWithCredentials(Object self, Object credentials_val, Object *clientEnv_ptr)
{
  ObjectArg a[2]={{{0,0}}};
  a[0].o = credentials_val;

  int32_t result = Object_invoke(self, IClientEnv_OP_registerWithCredentials, a, ObjectCounts_pack(0, 0, 1, 1));

  *clientEnv_ptr = a[1].o;

  return result;
}

static inline int32_t
IClientEnv_loadCmnlibFromBuffer(Object self, const void *cmnlibElf_ptr, size_t cmnlibElf_len)
{
  ObjectArg a[1]={{{0,0}}};
  a[0].bi = (ObjectBufIn) { cmnlibElf_ptr, cmnlibElf_len * 1 };

  return Object_invoke(self, IClientEnv_OP_loadCmnlibFromBuffer, a, ObjectCounts_pack(1, 0, 0, 0));
}

static inline int32_t
IClientEnv_configTaRegion(Object self, uint64_t appRgnAddr_val, uint32_t appRgnSize_val)
{
  ObjectArg a[1]={{{0,0}}};
  struct {
    uint64_t m_appRgnAddr;
    uint32_t m_appRgnSize;
  } i;
  a[0].b = (ObjectBuf) { &i, 12 };
  i.m_appRgnAddr = appRgnAddr_val;
  i.m_appRgnSize = appRgnSize_val;

  return Object_invoke(self, IClientEnv_OP_configTaRegion, a, ObjectCounts_pack(1, 0, 0, 0));
}

static inline int32_t
IClientEnv_adciAccept(Object self)
{
  return Object_invoke(self, IClientEnv_OP_adciAccept, 0, 0);
}

static inline int32_t
IClientEnv_adciShutdown(Object self)
{
  return Object_invoke(self, IClientEnv_OP_adciShutdown, 0, 0);
}



