# Use the current MSM_ARCH as the target config/ Makefile
# Since Kernel SI can support multiple ARCH's this allows only the current selected target ARCH
# to compile.
ifneq ($(CONFIG_QTI_QUIN_GVM), y)
ifneq ($(CONFIG_ARCH_QTI_VM), y)
include $(CAMERA_DEVICETREE_ROOT)/config/$(MSM_ARCH).mk
endif
endif

always-y	:= $(dtbo-y) $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
